# Generated by Django 4.0.6 on 2022-07-12 08:09

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='photos/products', verbose_name='Image'),
        ),
    ]
