# Generated by Django 4.0.6 on 2022-08-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='image',
            new_name='images',
        ),
    ]
