# Generated by Django 4.0.6 on 2022-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_value',
            new_name='color',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_category',
        ),
        migrations.AddField(
            model_name='variation',
            name='size',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
