# Generated by Django 4.0.6 on 2022-07-14 11:59

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_color_variation_variation_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='image',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='productgallery',
            name='images',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='store/products', verbose_name='Image'),
        ),
    ]
